### ISSUE TITLE
Error creating new RADON workspace

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#24]
If an user try to create/open a RADON workspace and another RADON workspace has been already opened by another user, the following error occurs:

Error Failed to run the workspace Failure executing POST at https10.96.0.1apiv1namespacescheservices. Message services radon-gmt already exists. Received status Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=radon-gmt, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services radon-gmt already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).

**Comment by miwurster** [comment]
Hi @sdagostini, I also experienced this error in my environment. This error is raised because old workspaces didn't clean up every Kubernetes resource on the underlying cluster --> I needed to delete the `radon-gmt` service by myself.

The following `devfile` config creates this Kubernetes service: 

```
    endpoints:
      - name: radon-gmt
        port: 8080
        attributes:
          protocol: http
          secure: "false"
          discoverable: "true"
          public: "true"
```

IMHO this is a bug in Eclipse Che. WDYT?

**Comment by sdagostini** [comment]
Hi @miwurster, I experimented this error when two different user are using at the same time a RADON workspace. At the moment it sems that 2 different users can not simultaneously use 2 different workspaces. I think that this error could be related to the configuration on the winery.yaml file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: winery-deployment
  labels:
    app: winery
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winery
      tier: frontend
...
```

The "replicas" field is set to 1, maybe we have to set more replicas in order to make available more replicas of the GMT to the users (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/).

What do you think?
