### ISSUE TITLE
The DPT plugin works on different workspaces except the RADON workspace

### ISSUE THREAD

**Issue by stefanodallapalma** [radon-h2020/radon-ide#50]
Hi, 

I created a sidecar container for the DPT plugin in order to install a few python dependencies that are used by the plugin to extract Ansible and Tosca metrics.
The new meta.yaml is available [here](https://github.com/radon-h2020/radon-plugin-registry/blob/master/radon/radon-defect-predictor/latest/meta.yaml).
It is very similar to the meta.yaml of other plugins, but it has an additional field `containers` where I set up mine.
As you can see, I set up feasible memory and cpu constraints for the container.
Although I can perfectly use the plug-in in different workspaces (i.e., the one in "Getting started" in Eclipse Che), I cannot use it in the Radon workspace.
More specifically, when I use the provided [devfile](https://github.com/radon-h2020/radon-ide/blob/master/devfiles/radon/v0.0.4/devfile.yaml), I receive the following error:

``` 
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspaceh2507mtpfb3vts67.workspace-687668947c-sjw86" is forbidden: [maximum cpu usage per Pod is 14, but limit is 22335m., maximum memory usage per Pod is 7Gi, but limit is 11993907200.]', 'workspaceh2507mtpfb3vts67.workspace-687668947c'"
```

However, if you remove the `endpoints` from the current devfile, thus leaving only the plugins, it works.

```
components:
  - type: cheEditor
    reference: 'https://raw.githubusercontent.com/OpenTOSCA/che-winery-extension/master/deploy/che-theia.yaml'
    alias: theia-editor
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-vt/latest/meta.yaml
    alias: radon-vt-chePlugin
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-decomposition/latest/meta.yaml
    alias: radon-dt
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-defect-predictor/latest/meta.yaml
    alias: radon-dpt
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-menu/latest/meta.yaml
    alias: radon-menu
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-xopera-saas/latest/meta.yaml
    alias: radon-xopera-saas
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-template-library/latest/meta.yaml
    alias: radon-template-library-plugin
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-ctt/latest/meta.yaml
```

I guess there is some conflicts in terms of resources usage. Perhaps the [`globalMemoryLimit`](https://github.com/radon-h2020/radon-ide/blob/master/devfiles/radon/v0.0.4/meta.yaml) should be increased?

@sdagostini can you investigate this, please?

Thank you in advance.
